name: Security Scan

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2 AM

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for security scan
      run: |
        echo "Building Docker image for security scanning..."
        ./build.sh build-image -b ubuntu
        
        # Verify the image was built successfully
        docker images | grep flutter-docker-builder || (echo "❌ Docker image build failed" && exit 1)
        echo "✅ Docker image built successfully"

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'flutter-docker-builder:ubuntu'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Check if Trivy results exist
      run: |
        if [ -f "trivy-results.sarif" ]; then
          echo "✅ Trivy scan completed successfully"
          ls -la trivy-results.sarif
        else
          echo "❌ Trivy scan failed - no results file generated"
          exit 1
        fi

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('trivy-results.sarif') != ''
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Trivy vulnerability scanner (table)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'flutter-docker-builder:ubuntu'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH' 